notifications:
  recipients:
    - activeldap@ml.commit-email.info

dist: xenial

addons:
  apt:
    packages:
      - ldap-utils
      - slapd

rvm:
  - 2.4
  - 2.5
  - 2.6

before_script:
  - password="secret"
  - encrypted_password=$(slappasswd -s ${password})
  - |
    (echo "version: 1";
     echo "dn: olcDatabase={1}mdb,cn=config";
     echo "changetype: modify";
     echo "replace: olcRootPW";
     echo "olcRootPW: ${encrypted_password}";
     echo "-") | sudo ldapmodify -Y EXTERNAL -H ldapi:///
  - sudo ldapmodify -Y EXTERNAL -H ldapi:/// -f test/add-phonetic-attribute-options-to-slapd.ldif
  - base="dc=$(echo get slapd/domain | sudo debconf-communicate slapd | sed -e 's/^0 //' | sed -e 's/^\.//; s/\./,dc=/g')"
  - |
    (echo "test:";
     echo "  host: 127.0.0.1";
     echo "  base: dc=test,${base}";
     echo "  bind_dn: cn=admin,${base}";
     echo "  password: ${password}") > test/config.yaml
