name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: ${{ matrix.ruby }} & ActiveModel ${{ matrix.activemodel }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby-2.4
          - ruby-2.5
          - ruby-2.6
          # - ruby-2.7
          - jruby-9
        activemodel:
          - "4"
          - "5"
        exclude:
          - ruby: ruby-2.6
            activemodel: "4"
          - ruby: jruby-9
            activemodel: "4"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: >-
          docker-compose run
            ${{ matrix.ruby }}-activemodel-${{ matrix.activemodel }}
